
#ifndef DISPEXTERN_H_INCLUDED
#define DISPEXTERN_H_INCLUDED

#define FACE_ID_BITS 20

enum lface_attribute_index
{
  LFACE_FAMILY_INDEX = 1,
  LFACE_FOUNDRY_INDEX,
  LFACE_SWIDTH_INDEX,
  LFACE_HEIGHT_INDEX,
  LFACE_WEIGHT_INDEX,
  LFACE_SLANT_INDEX,
  LFACE_UNDERLINE_INDEX,
  LFACE_INVERSE_INDEX,
  LFACE_FOREGROUND_INDEX,
  LFACE_BACKGROUND_INDEX,
  LFACE_STIPPLE_INDEX,
  LFACE_OVERLINE_INDEX,
  LFACE_STRIKE_THROUGH_INDEX,
  LFACE_BOX_INDEX,
  LFACE_FONT_INDEX,
  LFACE_INHERIT_INDEX,
  LFACE_FONTSET_INDEX,
  LFACE_DISTANT_FOREGROUND_INDEX,
  LFACE_EXTEND_INDEX,
  LFACE_VECTOR_SIZE
};

#define FACE_TTY_DEFAULT_COLOR ((unsigned long) -1)

#define FACE_TTY_DEFAULT_FG_COLOR ((unsigned long) -2)

#define FACE_TTY_DEFAULT_BG_COLOR ((unsigned long) -3)

#define MAX_FACE_ID ((1 << FACE_ID_BITS) - 1)

#endif
